#!/bin/bash
grunt
mv /Users/phoenix/Devel/korsakow/korsakow-js-player/dist/player/data/js/korsakow_player.js /Users/phoenix/Sites/mytestoutput/data/js/korsakow_player.js 
open /Applications/Google\ Chrome.app http://127.0.0.1/~phoenix/mytestoutput
